[package]
name = "backlogr-taiga"
edition = "2024"
license.workspace = true
version.workspace = true

[dependencies]
minreq.workspace = true
facet.workspace = true
facet-json.workspace = true
eyre.workspace = true
color-eyre.workspace = true
clap = { version = "4.5.40", features = ["derive"] }
